assets/where_are_my_files.txt, main.nf
This should fix #39 and provide better output handling in cases where e.g. reference genome data is not stored properly.
=> Cleaning up my closet

docs/usage.md
- [x ] This comment contains a description of changes (with reason)
=> Small backtick typo removed

main.nf
This is just docs / help function updates, also checking with James suggestion in 
https://github.com/nf-core/eager/issues/56
=> Add more help text to the pipeline

.travis.yml, docs/usage.md, main.nf
This fixes https://github.com/nf-core/eager/issues/61 
and adds CircularMapper again to EAGER2.0!
=> Adds Circularmapper functionality back

.travis.yml, docs/usage.md, main.nf
Fix for https://github.com/nf-core/eager/issues/51
=> Require either --singleEnd or --pairedEnd

.travis.yml, CHANGELOG.md, Dockerfile, Singularity, environment.yml, nextflow.config
This adds a test case for conda to Travis
Should fix https://github.com/nf-core/eager/issues/71
=> Conda testing

main.nf
=> Added --dedupper options

docs/usage.md
=> Fixed typo for multiqc_config

.travis.yml, Dockerfile, Singularity, environment.yml, nextflow.config
=> Created PR for release 2.0.3

CHANGELOG.md, conf/base.config
This should just add sane defaults for BWA mem.
=> Add sane defaults for BWA mem

.travis.yml, CHANGELOG.md, Dockerfile, Singularity, conf/test.config, environment.yml, main.nf, nextflow.config
Shamelessly self-merging this one :-)
=> PR Bump for 2.0.4 

CHANGELOG.md, docs/faq.md, docs/troubleshooting.md
=> Added troubleshooting pipeline updating

.travis.yml, CHANGELOG.md, Dockerfile, Singularity, conf/test.config, environment.yml, main.nf, nextflow.config
This adds testing for more than one sample to the pipeline.
=> Improve pipeline tests

docs/usage.md
=> Made more specific --bwa_index is path to dir

.travis.yml, CHANGELOG.md, Dockerfile, Singularity, environment.yml, nextflow.config
This updates `dev` with required changes for 2.0.5 release
=> Version 2.0.5 PR for release

environment.yml
=> Bump environment versions

docs/usage.md
Emphasis on each process, not the overall nextflow submission.
=> Further clarification on `--max-cpus`

README.md
Added some instructions in README to make the workflow run with the test dataset.
- [X ] This comment contains a description of changes (with reason)
=> Update README.md with instructions for test data

nextflow.config
=> Remove if clause here

main.nf
=> Fix remaining issue with circularmapper

main.nf
=> Fix cardinality issues

CHANGELOG.md, docs/usage.md
=> Polish usage, add changelog 

.travis.yml, CHANGELOG.md, Dockerfile, Singularity, environment.yml, nextflow.config
=> PR for release 2.0.6

CHANGELOG.md, README.md
=> Missing some details

nextflow.config
=> Fix custom config version

.travis.yml, Dockerfile, Singularity, environment.yml, nextflow.config
=> Bump to dev version

conf/base.config, nextflow.config
=> Get in line with nf-core tools v1.5 best practices

docs/configuration/adding_your_own.md, docs/installation.md, docs/usage.md
Started improving `-profile` section of docs
Issue: Reference in #175 
=> Profile description improvement

docs/usage.md
=> Added cleanup paragraph to usage docs

CHANGELOG.md, main.nf
Fix https://github.com/nf-core/eager/issues/183
=> Fix dedup bam

main.nf
Also tweaked flag descriptors for both for explicitness
=> Added skip-fastQC & moved stripping up

bin/extract_map_reads.py, main.nf
To fix PR #189 :
- fixed typo
- renamed flags in python scripts to be more intuitive
- added strip_mode
=> Fix of #189

.travis.yml, CHANGELOG.md, conf/test_fna.config, nextflow.config
=> Just add more tests to `dev` to find errors in `dev`-> `master` branch update

bin/extract_map_reads.py
`extract_map_reads.py` now handles cases when the number of processes requested to parallelize bam parsing is greater than the number of chromosomes/genomes in the reference.
This solves the issues raised by @jfy133 
However Travis might fail because the Docker container tag requested (2.0.7) in the config file is not yet available on docker hub (ping @apeltzer ).
=> handle case when nb chr < nb processes

.travis.yml, Dockerfile, conf/base.config, environment.yml, nextflow.config
=> Fix DamageProfiler issues 

environment.yml
=> Fix python dependency to 3.6.3 for now

assets/multiqc_config.yaml, main.nf
=> Use prefix for raw reads fastqc multiqc results

main.nf
=> Slight tweaks to help message

CHANGELOG.md, main.nf
=> Add changelog and fix for issue with index

.travis.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
To get some of the smaller bugs fixed since 2.0.6 in the stable branch, bumping to 2.0.7.
=> Bumped to 2.0.7

docs/usage.md
Following: https://www.nextflow.io/blog/2019/demystifying-nextflow-resume.html
=> Added reference to `-work-dir`

README.md
=> Missed a backtick

.travis.yml, Dockerfile, environment.yml, nextflow.config
=> Bump to 2.0.8

environment.yml
Adds in FreeBayes for genotyping PR #238
=> Add in FreeBayes dependency

.travis.yml, CHANGELOG.md, README.md, main.nf, nextflow.config
Fix Travis CI and nf-core V1.7 template linting.
=> Fix TravisCI.com again

.github/workflows/nf-core_eager.yml
This transfers all current travis tests to GitHub actions.
All tests are working, remaining issue is getting job names correct for tower.nf reporting.
=> Travis to GitHub Actions Migration 

.github/workflows/branch.yml, .github/workflows/linting.yml, .github/workflows/nf-core_eager.yml
Switching down to explicitly Ubuntu 18.04 as a LTS (most likely more common on production machines)
=> GitHub actions secrets

.github/workflows/nf-core_eager.yml, .travis.yml, README.md, main.nf, nextflow.config
Lets try again...
Fixing https://github.com/nf-core/eager/issues/299
=> Allows supplying FAI/Dict and still run genotyping

CHANGELOG.md, environment.yml
Lets get this build over night ;-)
=> Bump mtnuc to 0.6

CHANGELOG.md, environment.yml
=> Revert "Revert "Bump mtnuc to 0.6""

CHANGELOG.md, environment.yml
Add Biopython and [xopen](https://github.com/marcelm/xopen/) dependancies to prepare for PR speeding up read stripping.
=> Update env to prepare for PR

environment.yml
PR to rebuild Docker container in preparation of the addition of Kraken2
=> Add pandas and Kraken2 dependancies for adding Kraken2 to eager

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, CHANGELOG.md, README.md, docs/usage.md, main.nf, nextflow.config
On the PR review for 2.1.0 release
=> Changes from PR review

README.md, docs/output.md, main.nf
=> Final changes from PR review hidden comments (hopefully)

.github/workflows/ci.yml, conf/test.config, docs/output.md, docs/usage.md, main.nf, nextflow.config
This removes the actually 'useless' `--paired-end` flag, based on the twitter results - to close #370 
=> Single end param fix

CHANGELOG.md, main.nf, nextflow_schema.json
=> Mini Schema Update and small bugfix

.github/workflows/ci.yml, main.nf
=> Fixes UG genotyping and MultiVCFAnalyzer

docs/faq.md
To help with: https://github.com/nf-core/eager/issues/385
=> Add explanation of sticked on revision

.github/workflows/ci.yml, assets/multiqc_config.yaml, docs/usage.md, main.nf, nextflow.config
=> Latest changes, now with strip FASTQ working with lane merging!

.github/workflows/ci.yml, docs/usage.md, main.nf
=> Improve tests

docs/output.md
=> Improve AdapterContent docs regarding pre- and post-AR FASTQC

README.md, docs/troubleshooting.md, docs/usage.md, main.nf
=> Add extra validation to direct input and standardise error messages

main.nf, nextflow.config
=> Bump MultiQC base resources because of crazy issue from @ZandraFagernas

nextflow.config
=> Re-add accidently removed nf-core config profile loading

CHANGELOG.md, main.nf
=> Updating Changelog for all TSV-input changes and code formatting 

main.nf
https://github.com/nf-core/eager/issues/209#issuecomment-626349292
=> Added sort to ensure R1 comes before R2 for consistency as reported

docs/output.md
Fixes broken image link in output
=> Fix broken FASTQC Seq. Quality Histogram

main.nf
Allows Aida to continue beta testing
To close https://github.com/nf-core/eager/issues/443
=> Patch markdups to copy output files not symlink

.github/workflows/ci.yml
See https://github.com/nf-core/rnaseq/pull/426 for reason - no more need to wait for DockerHub to build images upon changes. We can test this when new CircularMapper (mini bugfix is added to environment + bowtie2 as well...)
=> Docker Build on GHA + Upload to DockerHub

CHANGELOG.md, environment.yml
New PR, old one was broken :-(
=> Add in several new dependencies / bowtie2 / sequencetools 

main.nf
Adds a small patch for the two related issues in https://github.com/nf-core/eager/issues/454
Will now publish lane merged FASTQs and the merged BAMs from initial merging (un-trimmed ones)
=> Published lanemerged FASTQs and lib merged BAMS and remove some TODOs

main.nf, nextflow.config
Update bwa_index default value so it's in string (as would be given by user), to fix AWS error reported internally by @apeltzer 
=> Bwa index patch

CHANGELOG.md, main.nf
This should fix #473 and also address then afterwards the index issues we experienced so far :-) (later to be added to the branch I'm working on right now).
=> Fix for https://github.com/nf-core/eager/issues/473 

CHANGELOG.md, main.nf
=> Add preserve realign + index

.github/workflows/ci.yml, CHANGELOG.md, docs/usage.md, nextflow.config
This is to close #508 , as DeDup is only applicable in very specific contexts whereas markduplicates runs in most cases
=> Dedupper default

.dockstore.yml, CHANGELOG.md
Adds a .dockstore.yml file to test updating our Dockstore integration :-) Should be put later under `.github/.dockstore.yml`, once Dockstore has support for this 👍
=> Add dockstore.yml

nextflow_schema.json
New pipeline schema structure. See nf-core/tools#696
=> Update schema to use new definitions groups

CHANGELOG.md, bin/print_x_contamination.py
"Num_SNPs" was missing form the header.
=> Fixed header of nuclear_contamination.txt

.github/workflows/awsfulltest.yml
=> Try patching AWS fulltest command

.github/workflows/awstest.yml
=> Also update aws test

CHANGELOG.md, environment.yml
=> Fix DeDup 

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
On the tin. Read group bugs/fixes from @IdoBar and additional schema fix for value types.
=> Patch release with readgroup fixes and to get docker working

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Post-release version bump

CHANGELOG.md, environment.yml
=> Bump MQC to 1.10 for other patches

CHANGELOG.md, environment.yml, main.nf
=> Get latest dev

README.md
=> added myself as contributor

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Post release version bump

Dockerfile
A lot of the automated PRs for this patch release failed, but as it was such a simple update we were too lazy to manually prep them 👀 
Here it is anyway! 🚀
=> Template update for nf-core/tools version 1.13.3

conf/benchmarking_vikingfish.config
=> Update AWS test reference to s3 bucket version

CHANGELOG.md, main.nf, nextflow.config, nextflow_schema.json
=> Add Bt2 --maxins

CHANGELOG.md, main.nf, nextflow.config, nextflow_schema.json
Add bwa aln `-o` flag to _begin_ to address https://github.com/nf-core/eager/issues/722
Note this doesn't modify the mapping parameters (we should do that in a major release) but one parameter recommended to change is this one.
:warning: merge #742 first!
=> Add bwa -o flag

main.nf, nextflow_schema.json
=> Get upstream fixes for tests to pass

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, CHANGELOG.md, Dockerfile, README.md, docs/usage.md, lib/NfcoreSchema.groovy, main.nf, nextflow.config, nextflow_schema.json
=> Get latest dev into wangen base

CHANGELOG.md, main.nf
=> Workflow summary fix

CHANGELOG.md, bin/scrape_software_versions.py, main.nf
Originally approved [here](https://github.com/nf-core/eager/pull/759/), but that branch got messy due to unrelated issue (fix coming in new PR)
=> Software version fix

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Version bump for patch release prep

README.md
Idea shamelessly stolen from @maxibor
=> Add PeerJ Badge

CHANGELOG.md, docs/output.md
Removing unclear/confusing phrasing
=> Improve BoeTiw2 output documentation 

CHANGELOG.md, README.md, main.nf
To close #787 
And an addition bug re: MVA (when supplying already made VCFs, only these would run and not the newly generated ones)
=> Fix GATK memory specs and MVA add vcf files

CHANGELOG.md, main.nf
To close #792 
Tested manually. Less efficient, but results in much less debugging headaches
=> Adapterremovalfixprefix sep

.github/workflows/ci.yml, CHANGELOG.md, README.md, conf/test.config, conf/test_direct.config, docs/usage.md, nextflow.config
=> Test tsv to test

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Post release bump

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Verision bump 2.4.1

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Version-bump

.github/workflows/ci.yml, CHANGELOG.md, main.nf
Fixes #838 
And adding a test for it...
also possibly fix an issue with PMDtools and reference masking, but I don't understand what is going on there so need input from @TCLamnidis
=> Fix snpcapture_bed

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
Starting again over #861 due to accidental merge to master
=> Bump Versions for patch releease

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Bump versions for patch release - PR from bump-vers into dev

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
=> Post-release bump

.github/workflows/ci.yml, Dockerfile, environment.yml, nextflow.config
Verison bump for quick patch release
=> Bump version for patch

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, main.nf, nextflow.config
Single change: fixing bed files being consumed.
=> 2.4.4 patch release

CHANGELOG.md, main.nf
=> Fastqc thread fix

CHANGELOG.md, main.nf
=> Fix circulargenerator assuming .fasta extension

CHANGELOG.md, nextflow_schema.json
=> Defaults fix

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, nextflow.config
* `nf-core bump-version 2.4.5dev` (nf-core version `1.14`)
* Add `dev` to CHANGELOG.md
*  Also correct date for released version 2.4.5
=> dev version bump

CHANGELOG.md, bin/endorS.py
=> Endorspy license change

CHANGELOG.md, main.nf
I now remember why we had it in the first place :roll_eyes:
=> Re-add picard createorreplacereadgroups for MultiVCFanalyzer

CHANGELOG.md, environment.yml
MultiQC to official 1.13 release
Add MALT to pin to working version (0.61)
=> Patch release dependency updates

conf/test_humanbam.config
Set reference of human bam to a human chr21 fasta.
=> update reference of test_humanbam

.github/workflows/ci.yml, CITATIONS.md, conf/modules.config, docs/output.md, modules.json, modules/nf-core/bowtie2/align/main.nf, modules/nf-core/bowtie2/align/meta.yml, nextflow.config, nextflow_schema.json, subworkflows/local/map.nf
=> DSL2: Adding Bowtie2

CITATIONS.md, conf/modules.config, docs/development/manual_tests.md, docs/output.md, modules.json, modules/nf-core/damageprofiler/main.nf, modules/nf-core/damageprofiler/meta.yml, nextflow.config, nextflow_schema.json, subworkflows/local/calculate_damage.nf, workflows/eager.nf
=> DSL2: Damageprofile

.github/workflows/ci.yml, workflows/eager.nf
=> Fix CI tests

CITATION.cff, assets/email_template.html, conf/modules.config, docs/development/manual_tests.md, docs/output.md, modules.json, modules/nf-core/cat/cat/environment.yml, modules/nf-core/cat/cat/main.nf, modules/nf-core/cat/cat/meta.yml, nextflow_schema.json, subworkflows/local/metagenomics_postprocessing.nf, subworkflows/local/metagenomics_profiling.nf
Update for metagenomics dsl2 conversion --
- outputting of malt logs is fixed in parallel execution mode.
- execution of maltextract is fixed in parallel executino mode
NOTE: taxpastamerge currently broken with test data used. will fix next week.
NOTE: linting must be done on dls2-metagenomics branch prior to merging into dev
=> DSL2: metagenomics testing for malt fixes

conf/test_kraken2.config, modules.json, modules/nf-core/untar/environment.yml, modules/nf-core/untar/main.nf, modules/nf-core/untar/meta.yml, nextflow.config, nextflow_schema.json, subworkflows/local/metagenomics_profiling.nf
Test profile for kraken2 and added the UNTAR module that can be used for the other databases as well!
=> Add kraken2 test-profile, add UNTAR module

conf/test_malt.config, nextflow.config
Malt testing config, thanks @merszym for the untar module -- works great :)
=> added config for malt testing

conf/modules.config, workflows/eager.nf
Adding merging of libraries of the same sample and publication of resulting bam files
Closes #1065
=> DSL2: raw library merging + publishing

bin/collect_genotypes.py
- minor fixes to helptext of an auxilliary script.
=> Minor changes to auxilliary script

conf/modules.config
Fix #968 
SAMTOOLS_LENGTH_FILTER_INDEX|SAMTOOLS_FILTER_INDEX published indexes without checking params.bamfiltering_savefilteredbams
=> check params.bamfiltering_savefilteredbams for bai

.github/workflows/ci.yml, CHANGELOG.md, Dockerfile, environment.yml, main.nf, nextflow.config
=> Fix typo in variable name for UG IndelRealigner  -targetIntervals variable
