nf-core/eager

- docs/installation.md
- docs/usage.md
Switch `--fasta` and `--genome` flag descriptions as I think people are more likely to use their own lab's default references than iGenomes.
It could confuse things if a new user came in and isn't aware of the difference.
Futhermore, added to the `docs/installation.md` file a list of software used within the pipeline. I might also add the citations down the line. Feel free to move if in the wrong place.
- [x ] This comment contains a description of changes (with reason)
> Switched --fasta and --genomes descriptions, added software links

- .travis.yml
- main.nf
- nextflow.config
This adds optional bam trimming for UDGhalf protocols for example. Users can specify how many bases should be clipped off reads at start/end after mapping and this will be done.
> Bamtrim udghalf

- docs/usage.md
> Memory requirements

- .travis.yml
- CHANGELOG.md
- Dockerfile
- README.md
- Singularity
- environment.yml
- nextflow.config
Fixing some minor bugs in 2.0.0 release.
> PR for release 2.0.1

- .travis.yml
- CHANGELOG.md
- environment.yml
- main.nf
This should address #79 and resolve these open points once finished.
> Index file handling fixing #79

- CHANGELOG.md
- main.nf
> Fix samtools index #84

- CHANGELOG.md
- conf/binac.config
- docs/usage.md
- environment.yml
- main.nf
- nextflow.config
This renames a couple of things to different names, to make sure people understand what these options mean. 
cf https://github.com/nf-core/eager/issues/76 
Namely:
bam_keep_mapped_only ==> bam_analyse_mapped_only
bam_filter_reads ==> bam_retain_all_reads
> Adjustments for #76 , rename certain options to be more explicit

- docs/installation.md
- docs/usage.md
Trying to reduce confusion for novice users (who I would argue EAGER is some what geared towards) by putting bash profile stuff in installation. I assume whoever is installing this can configure the bash_profile for themselves (if single user installing nextflow/eager) or a system admin could set this variable for everyone.
> Some documentation shuffling to account for users vs administrators

- CHANGELOG.md
- conf/multiqc_config.yaml
- main.nf
This should fix the remaining MULTIQC order things...
> Fix mqc section orders

- CHANGELOG.md
- main.nf
This puts all files into separate channels to follow best practices with data staging in Nextflow.
> Files in channels (follow best practices)

- .travis.yml
- CHANGELOG.md
- docs/configuration/reference_genomes.md
- docs/usage.md
- main.nf
Adds support for gzipped FastA reference genome input.
> Enable gzipped FastA input as reference genome

- CHANGELOG.md
- docs/usage.md
- main.nf
This addresses https://github.com/nf-core/eager/issues/89 directly, also documenting the changes in both changelog and user documentation.
> Fix redundant UDG flags

- CHANGELOG.md
- docs/usage.md
- main.nf
This should address the error in #130 and your issues @jfy133 :-) 
Automatically renames any `--fasta` reference genome to use the `*.fasta` file extension if its not present already 👍
> Rename reference to fasta in all cases

- main.nf
General clarifications for index files (to sync with docs), FastP and general typo corrections and re-ordering.
Question for @apeltzer - what is the default bam_discard_unmapped output format? Should we set one?
> Extra clarifications for indices, FastP and general cleanup

- CHANGELOG.md
- conf/base.config
- main.nf
> Fix picard memory issue

- CHANGELOG.md
- README.md
- docs/usage.md
- main.nf
- nextflow.config
This addresses #146 , where the contig sizes are too long for the regular BAI indices used in the default `samtools index` process. x-ref https://www.biostars.org/p/111984/ it doesn't really harm to use CSI indices, so I just use these now everywhere instead, which should work both on smaller and larger reference genomes without issues 👍 
> Fix Samtools indexing for large reference genomes

- CHANGELOG.md
- main.nf
Addressing https://github.com/nf-core/eager/issues/154
> Adding in publishing dedup log files as well

- CHANGELOG.md
- conf/base.config
- environment.yml
- Adds in a fix for damageprofiler when output is too small to show even results
- Adds mtnucratio and dedup recipes to get new JSON output for future multiqc reporting ;-) 
> Bugfix for Damageprofiler, also new deps adding

- conf/multiqc_config.yaml
The path originally used failed to picked up FastQC files if you had e.g. performed polyG trimming. The new regex now picks up any FastQC file that has 'combined' in the name. This still isn't perfect but we can fix it once the new prefix system is in. 
> fixed multiqc config too-strict post-AR path

- conf/multiqc_config.yaml
in approximate order of EAGER1, and a couple of extra columns.
> Default general stats column display and ordering

- CHANGELOG.md
- docs/usage.md
- main.nf
This adds making FastQC optional in the beginning.
> Add Skipping FastQC 

- .travis.yml
- CHANGELOG.md
- conf/base.config
- environment.yml
- main.nf
- nextflow.config
Trying to fix couple of stuff , e.g. fasta reference naming, indexing availability without channels so we can re-use them efficiently.
> Fix ref genomes & other behaviour

- CHANGELOG.md
- main.nf
> Fix remaining issues with indices for non-fasta endings

- .travis.yml
- Dockerfile
- environment.yml
- nextflow.config
> PR for 2.0.PR for 2.0.77

- CHANGELOG.md
- main.nf
Fixing couple of relicts in the code that @jfy133 spotted. 
> Minor fixes + additional tests

- main.nf
> Fixing minor help message typo

- CHANGELOG.md
- assets/multiqc_config.yaml
- docs/output.md
- main.nf
This PR duplicates the samtools flagstat step for after mapping quality filtering. This allows a user to see the effect of mapping quality filtering.
It also includes some clean-up of code comments
Note: I've manually tested this  myself. The only thing that is slightly off is that the General Stats table doesn't report the name of which samtools flagstat step it is from (but it displayes pre- and post- map quality filtering in the correct order). However the menu on the left does have the correct names.
> Added post-mapping filter statistics generation

- README.md
> Added clean intermediate files section to README

- .travis.yml
- CHANGELOG.md
- docs/usage.md
- main.nf
This extends options for AdapterRemoval, namely:
1) preserve 5p (doesn't do quality trimmed at generally higher quality 5p ends, to prevent issues during deduplication) https://github.com/nf-core/eager/issues/226
2) use only merged reads downstream from AdapterRemoval for higher quality e.g. genotyping https://github.com/nf-core/eager/issues/212
@apeltzer the linting fails for [#5](http://nf-co.re/errors#5) but I'm not sure why because the line it refers to is in `.travis.yml`. Any ideas?
> Adapter removal updates

- .github/markdownlint.yml
- docs/output.md
Tweaking markdown linting to allow doc image justification
Allows `p` (for center justifying) and `img` (for resizing) tags
> Tweaking markdown linting to allow doc image justification

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
I just realised hte updated PR info template was not displaying. It wasn't in the right place - should be fixed now according to https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
> Pr template fix

- main.nf
Small fix reducing overly strict input (redundent) requirements, as indexing self-performed by gatk_ug3.5 module
> Removed redundant input process from UG as self-indexes

- CHANGELOG.md
- environment.yml
Reverts nf-core/eager#307 as the new conda build for MtNucRatio doesn't work!
```
fellows@datpx11799:~$ mtnucratio 
Error: Unable to access jarfile /home/fellows/miniconda3/share/mtnucratio-0.6-0/MTNucRatioCalculator-0.5.jar
```
> Revert "Bump mtnuc to 0.6"

- CHANGELOG.md
- conf/base.config
- docs/usage.md
- environment.yml
- main.nf
This includes a range of bug fixes and enhancements
1. Generalises default resource requirements rather than process specific settings with `withLabel` to address https://github.com/nf-core/eager/issues/310
2.  Fixes a bug reported by Marcel Keller that genotyping was only running for one sample. This was due to the reference FASTA being consumed. I also expanded to ensure all processes have independent FASTA input channels. (thanks to @drpatelh @mahesh-panchal for troubleshooting)
3. Adds an ignore for pipe errors (exit code 141) for pmdtools as pmdtools still fails even if samtools says 'err no'
4. Adds documentation for pipeline specific institutional profiles.
5. Fixes an instability with using `tee` for samtools which was trying to paralellise within a paralellised process
**Learn …
> Resource requirement and abstraction process fixes 

- CHANGELOG.md
- bin/extract_map_reads.py
- main.nf
In `strip_input_fastq` process
Improves the speed **very** slightly
> Move extract map reads fastq compression to pigz

- conf/base.config
This PR fixes a small 'bug' due to Java reporting an exit code as 1, if the heapspace runs out of memory.
Adding exit code 1 to a 'retry' rather than finish, at least gives the recently added MALT a chance to get enough memory before running out due to retry-limit. 
> Bugfix MALT error retries

- README.md
Minor documentation change. Unfortunately nextflow doesn't actually stop if the user's version is not the one listed in the manifest.
> Added minimum nxf ver to README

- main.nf
On the tin, is a minor patch to previous 2.1.0 prep PR. Basically in the input channel creation when not running bam filtering, add to the map a third 'dummy' element, but also add a condition that this isn't used within the endorS.py when bam filtering is not run.
> Remove input cardinality warning for endorS.py when no bam filtering

- .github/workflows/ci.yml
To make Github Actions more extensive, and more clean switched all tests that can be run on both single and paired end samples to use the matrix to close #364 .
> Cleans up endedness matrix for Github Actions

- CHANGELOG.md
- README.md
- conf/test.config
Added `--paired_end` to the test profile
> Added paired-end parameter to test profile

- main.nf
Really small FASTQC label bump to 4GB memory to close https://github.com/nf-core/eager/issues/378
> Bump up FASTQC base resources

- docs/usage.md
Just found a case where I didn't have `mail` or `sendmail` installed on my laptop, and `--email` was hitting funny errors. Clarified in docs.
> Add caveat dependencies when running with --email

- CHANGELOG.md
- docs/usage.md
- nextflow.config
This updates the default BWA mapping parameters to the actual recommended settings in Schubert et al. 2012 (https://doi.org/10.1186/1471-2164-13-178), which is keep mismatch rate at 0.04 but turn off seeding. 
I mis-read the paper and originally set the helicos parameters.
> Mapping params update

- main.nf
Makes it so the non-log output files of DamageProfiler doesn't crash the pipeline, if not generated because no reads in the BAM. i.e. DamageProifler worked correctly, input BAM just had not enough reads. To close #434 
> Patch damage profiler so if no reads doesn't crash

- main.nf
Replaces the 'path' tag with an actual string, to close #439 
> Fix for warning reported in #439

- main.nf
Original pileupcaller code would only run for a single sample then completing, as the bed/SNP files weren't `.collect()`ed and thus were consumed, stopping others from also being excecuted.
> Ensure all pileupcaller input channels filled for each sample

- assets/multiqc_config.yaml
- main.nf
This fixes an issue where due to tuple grouping during library merging, processes such as trim BAM would have 'ugly' names in the report (e.g `[ARD001]`, rather than just `ARD001`).
It does this by pulling the first entry of the libraryid grouped-tuple list. This _should_ always be a single value so it shouldn't matter. Then, I specify 'fake' library IDs of merged libraries for downstream tuples with the libraryid set to `${samplename}_libmerged", to indicate that a library is now 'complete'.
> Trimmed bam name patch

- assets/multiqc_config.yaml
- docs/usage.md
- main.nf
Removes references to legacy `--tsv_input`. To close #464 
As a bonus, this adds a dedupper validation check (previously missing), makes markduplicate running more stable and fixes the ordering of MarkDuplicates column in general stats table, to close #463 .
> Docs and Markduplicates patch

- .github/workflows/awsfulltest.yml
- .github/workflows/awstest.yml
This adds proper AWS Full tests and AWS Tests for eager. Maybe @ggabernet can have a look as she opened the ones at Sarek/ATACseq/.... ;-)
Full test profile will be available once we merge in #418 , until then this just runs `test_tsv` as profile.
> Add proper fulltests with org level secrets

- .github/CONTRIBUTING.md
- CHANGELOG.md
- README.md
- docs/usage.md
> Add some launch docs

- CHANGELOG.md
- assets/multiqc_config.yaml
- bin/print_x_contamination.py
- environment.yml
- main.nf
Various changes:
- Added latest version of Sex.DetERmine to `environment.yaml`. This version doesn't fail horribly when a bin has 0 coverage, instead setting the rates to 0.
- Removed second barplot (`snp_counts`) from multiqc_report. Not that useful, but easier to hide it than to change MQC modules. 
Nuclear_contamination changes:
- Added nuclear contamination JSON output into multiQC
- Order of columns fixed so they come after SexDet.
To Do:
> Added nuclear_contamination to MultiQC report as custom content.

- CHANGELOG.md
- bin/endorS.py
Updated version of endorS.py related to issue #492, increases decimals in multiQC Report and adds check when no reads in input fastq and no mapped reads in bam file
> Endorspy update

- conf/base.config
I learnt that process specific resource parameters _overwrite_ entirely any default settings and do not inherit. This ensures all eager specific process settings also have the default 'global ones'.
> Add base exit codes to try to labelled process settings

- CHANGELOG.md
- conf/base.config
- main.nf
To close https://github.com/nf-core/eager/issues/516
> Bedtools fix

- .github/workflows/ci.yml
- docs/usage.md
- main.nf
Merge trim-bam-fix into flxitrim
> Merge trim-bam-fix into flxitrim

- main.nf
Due to insufficient validation, if there was a typo name in a column (e.g. Color vs Colour), the corresponding column would evaluated as 'NULL' for every row and mess up downstream analyses. This adds a check that all columns headers are named correctly. This should close #541 
> Tsv headername validation

- main.nf
This is to address the instability of the awk command that occurs during CI testing, by replacing it with @maxibor 's python script.
> Replaced awk with python version of read filtering

- CHANGELOG.md
- conf/base.config
- conf/benchmarking_pathogenscreening.config
- conf/test.config
- conf/test_full.config
- conf/test_tsv.config
- conf/test_tsv_bam.config
- conf/test_tsv_complex.config
- conf/test_tsv_fna.config
- conf/test_tsv_humanbam.config
- conf/test_tsv_kraken.config
- conf/test_tsv_pretrim.config
This PR is to close #546. When users move on from the small tests, they may want to run their own test on 'real sized' data, which may exceed 2.h base walltimes. This bumps this up to 24.h, and sets limits for specific profiles (1h, to also speed up during CI pipeline exiting if crashes occur, given most test runs take ~2m) 
This includes changes from #544 , please merge that first (sorry, wrong checkout procedure...) 
> Timelimit mods

- CHANGELOG.md
- bin/print_x_contamination.py
Bugfix in definition of `nSNPs` within `print_x_contamination.py`. 
Coercion of `nan` and `-nan` to `N/A` for more consistent MultiQC table reporting.
Corrected the reported number of SNPs used for nuclear contamination to be in line with the output of the latest ANGSD version.
This PR correctly references the `dev` branch. 
> Bugfix. Corrected number of relevant SNPs and NAs in `print_x_contamination.py`.

- docs/usage.md
- main.nf
This adds a validation check that only a single TSV is supplied (i.e. restricts the use of `*.tsv` to prevent scary groovy errors).
This closes #551 
> Added check only single TSV is supplied.

- CHANGELOG.md
- main.nf
Privately reported issue where MultiQC craps out with exit code 1 when running with >1000 samples. Not sure why the error occurs atm, but as a quick work around I propose to bump resources to give MQC at least 8GB.
> Bump MultiQC resources for cases of >1000 samples

- bin/endorS.py
- bin/extract_map_reads.py
- bin/filter_bam_fragment_length.py
- bin/kraken_parse.py
- bin/merge_kraken_res.py
- bin/parse_snp_cov.py
- bin/print_x_contamination.py
Something I noted when reviewing nf-core/cageseq, is that some of the utility scripts might be useful outside of eager2 at points, so it is good to insert the author and a (short) version of the license in each of them.
> Script licenses

- .github/workflows/awsfulltest.yml
- .github/workflows/awstest.yml
> Use dev version of AWS templates

- docs/usage.md
Small change to docs.
- Added a link where users can download the 1240k bedfile when following the human popgen tutorial. 
- Corrected a small typo in said tutorial.
Now edited the correct branch. 
> Added link to 1240k bedfile. Typo.

- CHANGELOG.md
- main.nf
Makes sure a bwa_index channel is made when specifyin circularmapper, to close #610 
> Circular mapper fix

- CHANGELOG.md
- conf/base.config
- main.nf
> Improve memory and error handling of qualimap

- CHANGELOG.md
- nextflow_schema.json
This is to close #654 . It makes sures all integers defaults are actually integer values and not accidently in strings. It also adds an a enum for `bt2n` as acoording to bowtie2 docs can only be either 0 or 1.
This should hopefully fix launch GUI params.json issues during internal eager parameter validation
> Fix schema accidently strings values to correct integers

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- README.md
- environment.yml
- nextflow.config
Identified when looking at AWS test results: AWS pulls 20.04.1 which had a bug with nested-Nf parameters. Although 20.04.0 worked, .1 doesn't so we need to jump to the next stable release (20.07.1).
to close #631
> Min nf bump

- CHANGELOG.md
- conf/base.config
Stopped MultiQC being skipped when running on large datasets
> Fix mqc retry

- CHANGELOG.md
- main.nf
Kraken database loading fixed to `fromPath` method for channel creation
> Fix kraken db loading fromPath

- CHANGELOG.md
- conf/base.config
This PR adds exit code 140 for retry, which for a variety of schedulers (in particular *grid engine related), corresponds to a walltime limit-kill. 
e.g. 
https://sites.google.com/a/case.edu/hpcc/jobs/slurm-command-overview/exit-code-status
https://users.gridengine.narkive.com/ZyRamWD7/gridengine-users-exit-status-140
Reported by Megan Michel at SHH/EVA/Harvard.
> Added exit code 140

- main.nf
For this in in the previous PR java-tool-fixes, sorry!
> Remove left-over picard -Xms java flags

- CHANGELOG.md
- environment.yml
Checks are currently failing because MultiQC fails as there is a bug in the HOPS post-processing script. The bug has been fixed in HOPS 0.35, so this bumps the env.yaml.
> Upgrades HOPS so it doesn't cause MultiQC fail

- CHANGELOG.md
- main.nf
#693 reported that no colour chemistry validation occured. It actually did exist, I just mixed up groovy operators :sweat_smile: . This fixes that (and is tested).
> Fix Colour chem validation

- CHANGELOG.md
- main.nf
- nextflow.config
- nextflow_schema.json
> Adds AdapterRemoval qualitymax parameter

- CHANGELOG.md
- main.nf
Someone reported CirtularGenerator was crashing, and I discovered it was a memory issue as we didn't specify the `-Xmx` flag. Add this for a few tools.
Also added the forgotten CHANGELOG for the template merge :eyes:
> Add missing Xmx for Java tools

- Dockerfile
- nextflow_schema.json
This is a hipster fix of https://github.com/nf-core/tools/issues/973, before Kevin pushes it to nf-core/tools! will skip CHANGELOG accordingly
Basically the regex in template didn't account for nextflow parsed duration values. This fixes this.
> Nextflow duration fix

- CHANGELOG.md
- environment.yml
- Bumps pigz to 2.6
- removes tbb pinning
> Fix pigz issues

- main.nf
Thanks a lot for adding the `bt2_maxins` parameter.
I found an error in the command line, which causes it to be ignored.  Here is a one-line correction.
(No need to change the README, I am already listed).
> Fix --maxins parameter in paired-end bowtie2

- CHANGELOG.md
- lib/NfcoreSchema.groovy
- main.nf
This simply helps users who might be initially overwhelmed by the number of output directories where to find their multiqc report. 
To close #736 
:warning: Merge #742 first!
> Multiqc message on completion

- CHANGELOG.md
- main.nf
- nextflow.config
To address #723 and also a bit of code cleanup for consistent (following @ewels suggestion to replace `== ''` and `isEmpty()` like conditions with `null`)
:warning: need to merge #742 first!
> Fix null validation

- CHANGELOG.md
- main.nf
- nextflow_schema.json
Accidently missed a `!` when typing so CI tests were failing with bedtools, and noticed missing defaults in the schema.
> Fix bedtools annotation file condition and re-add defaults

- CHANGELOG.md
- main.nf
> Fix specified CPUs in piped commands

- CHANGELOG.md
- main.nf
This **HOPEFULLY** fixes the flakiness of all the `samtools filter` related issues that have been plaguing us for ages on GitHub actions.
Basically replaces `-o` with a redirect and specifically specifying BAM output with `-b`. Not sure why it worked, but after some debugging on #759 it appeared at least once to solve the issue.
> Replace samtools -o with redirect for stability in CI test

- CHANGELOG.md
- nextflow.config
- nextflow_schema.json
This sets bamutils trimming defaults to 0, and updates bwa aln mapping to best practices
To close #612 and to close #722
> Update best practise defults and bam trimming defaults

- CHANGELOG.md
- main.nf
> FIX: fix kraken file naming

- CHANGELOG.md
- main.nf
- nextflow.config
- nextflow_schema.json
Small quality of life change. Rather than hardcoding map and base quality filtering of `30` prior to pileupcaller genotyping, the two filters can now be custom set with `--pileupcaller_min_map_quality` and `--pileupcaller_min_base_quality`.
> Flexible filtering of reads for pileupcaller genotyping.

- CHANGELOG.md
- main.nf
- Fixed memory requirements of bedtools coverage. Closes [#824](https://github.com/nf-core/eager/issues/824)
> Bedtools process changes

- CHANGELOG.md
- main.nf
I accidently left debugging code rather than mixxing the trimmed files back into the input channel for lane merging 🤦‍♀
To cloe #822
> Fix post-ar trimming not being included in downstream analyses

- main.nf
The most recent version of pileupcaller removes the `.txt` suffix that previous versions added to the genotype files.
`eigenstrat_snp_coverage.py` could not find the input files because it expected these suffixes to be present. With these changes, the script will no longer expect a `.txt` suffix to its input files.
> Remove expected `.txt` suffix for snp coverage

- CHANGELOG.md
- main.nf
Replaces `-n` with `-N` to RETAIN read-pair info, not remove it in samtools fastq 🤦‍♀
Fixes #857
> Samtools fastq fix

- CHANGELOG.md
- main.nf
When we refactored in 2.4.3 files such as the bedfiles, we apparently forgot to make them value channels. Therefore in some cases they were only allowing execution of some processes (e.g. snpcapture qualimpa) against a single channel.
This converts those that I identified from queue back to value channels.
Closes #871
> Fix refactored 2.4.3 auxiliary files to value channels

- CHANGELOG.md
- main.nf
Signed-off-by: Lehmann_Fabian <fabian.lehmann@informatik.hu-berlin.de>
Cannot start DSL1 workflows with the newest Nextflow version. So I had to define the DSL version explicitly.
- [ x] This comment contains a description of changes (with reason).
> Define DSL1 explicitly, as Nextflow made DSL2 default

- CHANGELOG.md
- conf/benchmarking_human.config
- conf/benchmarking_vikingfish.config
> Remove deprecated params from benchmarking profiles

- CHANGELOG.md
- environment.yml
This uses the sneaky 13a veriosn of MultiQC on bioconda which includes the awesome fixes to AR2 plots from @NiemannJ!!
> Bump MultiQC so we get proper AR2 plots

- CHANGELOG.md
- main.nf
This PR corrects the staging of input bam files for the genotyping_pileupcaller process. 
Avoids rare cases where binding of volumes failed within singularity and caused the process to fail.
The issue was revealed when upstream changes were made to fix endorspy caching errors.
> Pileupcaller paths fix

- CHANGELOG.md
- main.nf
Add fix for damageprofiler edge case requiring FAI file.
> Try fix for damageprofiler sometimes needing a fai file

- bin/check_samplesheet.py
- subworkflows/local/input_check.nf
- workflows/eager.nf
This adds the `bam_reference_id` column to the input TSV, which should be non-NA for BAM input and specify the reference name for the bam. This id is then passed into the `meta` of the bam files as `reference`.
> DSL2: Update input check

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- environment.yml
- nextflow.config
Closes https://github.com/nf-core/eager/issues/983 and a broken conda environment
Tested by manually editing environment to bump the pygments to the minimal version as reported in teh error, and then linted with nf-core tools 1.9
> 2.4.7 Patch

- conf/test_humanbam.config
Added larger human reference fasta and angsd parameters to the test_humanbam profile
> DSL2: adapt test_humanbam profile

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- assets/multiqc_config.yaml
- docs/output.md
- environment.yml
- main.nf
- nextflow.config
- nextflow_schema.json
- Added option to use MapDamage instead of DamageProfiler for damage estimation. Also added options to downsample to a specified number of reads for damage calculation with mapDamage. 
- Fixed a niche error causing file name collisons.
Closes #1020.
Closes #1017.
Clsoes #1031.
> Dsl1 2.5.0

- conf/modules.config
- docs/development/dev_docs.md
- docs/development/manual_tests.md
- docs/output.md
- modules.json
- modules/nf-core/bedtools/maskfasta/environment.yml
- modules/nf-core/bedtools/maskfasta/main.nf
- modules/nf-core/bedtools/maskfasta/meta.yml
- nextflow.config
- nextflow_schema.json
- subworkflows/local/manipulate_damage.nf
- subworkflows/local/reference_indexing.nf
- subworkflows/local/reference_indexing_multi.nf
- subworkflows/local/reference_indexing_single.nf
- workflows/eager.nf
This adds the options to run PMDtools only on a specific part of the genome within the damage manipulation subworkflow. Input options are the mapping reference, an already masked fasta file and a bed file for masking of the mapping reference.
This closes #1029.
> DSL2: add reference masking for PMDtools

- conf/modules.config
Adds missing `ext.prefix` to FASTQC modules.
> add ext.prefix

- modules.json
- modules/nf-core/bwa/aln/environment.yml
- modules/nf-core/bwa/aln/main.nf
- modules/nf-core/bwa/aln/meta.yml
- modules/nf-core/bwa/index/environment.yml
- modules/nf-core/bwa/index/main.nf
- modules/nf-core/bwa/index/meta.yml
- modules/nf-core/bwa/mem/environment.yml
- modules/nf-core/bwa/mem/main.nf
- modules/nf-core/bwa/mem/meta.yml
- modules/nf-core/bwa/sampe/meta.yml
- modules/nf-core/bwa/samse/meta.yml
- subworkflows/local/map.nf
- workflows/eager.nf
Update BWA. This has the convenient side effect that the new BWA Docker images come in the right format and work with recent Docker versions. This should work around Docker's infamous deprecation errors in CI tests for eager.
> Bump BWA version

- conf/modules.config
- subworkflows/local/bamfiltering.nf
- workflows/eager.nf
While testing CircularMapper, I found out that providing `--fasta_largeref` caused half the pipeline to not execute. The reason was that BAM filtering once accounts for the BAI indices, so I made changes so the CSI indices are also picked if necessary.
A similar bug was also identified in the nf-core SWF BAM_SPLIT_BY_REGION, so I deactivated the `-c` option for SAMTOOLS_INDEX in that SWF, to avoid issues. The swf will need an upstream fix, but since we don;t publish these indices, it makes little difference here.
Also fixed the same issue when running flagstat on input bams
> Fix bam filtering

- conf/modules.config
Corrects the implementation of #1099. 
The approved way of excluding the versions.yml is with the `saveAs` attribute, not `pattern`.
Maybe this snippet should be added to all modules? 🤔
> exclude version.yml from publishDirs

- subworkflows/local/map.nf
BAM file names are sorted before merging in order to stabilise downstream headers by always including the first `shard_number` (also `lane` and `colour_chemistry`) in the header.
Supposed to close #1104
> DSL2: Sharding Tweaks

- subworkflows/local/map.nf
This should fix the failure of `test_multiref` with most mappers (e.g. `bwamem`).
(Sharded) read input channels were `combine`d with references, but for most mappers they were combined a second time later, resulting in duplicates. I hope this changes are valid and I'm not missing anything!
> Fix multiref mapping

- conf/modules.config
- conf/test_nothing.config
- subworkflows/local/metagenomics_profiling.nf
- subworkflows/local/reference_indexing_single.nf
- workflows/eager.nf
Tested with profiles:
- Restructrued all output directories to `section/tools/{data/stats}` structure.
- Also reordered the order of modules by section and relative order of operation/appearance.
- Fixed a small bug in preseq lc_extrap. (Closes #1117)
This works fine for test profile (as fa as I could see), but some moduels (e.g. `damageprofiler`, `qualimap`) break the system by having results be a subdirectory.
```
$ tree results/ -d
results/
├── authentication
│   ├── bedtools
│   │   └── stats
│   ├── damageprofiler
│   │   └── stats
│   │       ├── JK2782_JK2782_TGGCCGATCAACGA_BAM_Mammoth_MT_Krause
│   │       ├── JK2782_JK2782_TGGCCGATCAACGA_Mammoth_MT_Krause
│   │       └── JK2802_JK2802_AGAATAACCTACCA_Mammoth_MT_Krause
│   ├── endorspy
│   │   └── stats
│   ├── preseq
│   │   └── …
```
> DSL2 restructure output directories

- CHANGELOG.md
- subworkflows/local/utils_nfcore_eager_pipeline/main.nf
Call of template nf-core utils template checking of samplesheet is not necessary and currently bugged (behaves incorrectly with https file paths as inputs, raises errors for all other inputs, as expected, but not necessary to raise error).
Solution for nf-core/eager: remove call
Todo: broader fix for deeper nextflow issue, fix nf-core template
Related to #1114
> removal of bugged nf-core utils function call 
